// <auto-generated />
using BookStoreWebApi.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreWebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230727153847_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookStoreWebApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 75m,
                            Title = "Karagöz ve Hacivat"
                        },
                        new
                        {
                            Id = 2,
                            Price = 5m,
                            Title = "Hamlet"
                        },
                        new
                        {
                            Id = 3,
                            Price = 100m,
                            Title = "Mesnevi"
                        },
                        new
                        {
                            Id = 4,
                            Price = 15m,
                            Title = "Araba Sevdası"
                        },
                        new
                        {
                            Id = 5,
                            Price = 55m,
                            Title = "Kaşağı"
                        },
                        new
                        {
                            Id = 6,
                            Price = 150m,
                            Title = "Uçurtma Avcısı"
                        },
                        new
                        {
                            Id = 7,
                            Price = 100m,
                            Title = "Ateşten Gömlek"
                        },
                        new
                        {
                            Id = 8,
                            Price = 90m,
                            Title = "Çalukuşu"
                        },
                        new
                        {
                            Id = 9,
                            Price = 45m,
                            Title = "Tutunamayanlar"
                        },
                        new
                        {
                            Id = 10,
                            Price = 10000m,
                            Title = "Nutuk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
